=== sandiri-saiteja/Kothii/xml/green-campus.dtd
<!-- =========================================================
     GREEN CAMPUS SUSTAINABILITY ANALYTICS PORTAL
     DTD VALIDATION
     ========================================================= -->

<!ELEMENT greenCampus (
    resources,
    consumptionRecords,
    sustainabilityMetrics
)>


<!-- =========================================================
     RESOURCES
     ========================================================= -->

<!ELEMENT resources (resource+)>

<!ELEMENT resource (
    resourceId,
    resourceName,
    resourceType,
    unit,
    description
)>

<!ELEMENT resourceId (#PCDATA)>
<!ELEMENT resourceName (#PCDATA)>
<!ELEMENT resourceType (#PCDATA)>
<!ELEMENT unit (#PCDATA)>
<!ELEMENT description (#PCDATA)>


<!-- =========================================================
     CONSUMPTION RECORDS
     ========================================================= -->

<!ELEMENT consumptionRecords (consumptionRecord+)>

<!ELEMENT consumptionRecord (
    recordId,
    resourceId,
    consumptionValue,
    consumptionDate,
    campusLocation
)>

<!ELEMENT recordId (#PCDATA)>
<!ELEMENT consumptionValue (#PCDATA)>
<!ELEMENT consumptionDate (#PCDATA)>
<!ELEMENT campusLocation (#PCDATA)>


<!-- =========================================================
     SUSTAINABILITY METRICS
     ========================================================= -->

<!ELEMENT sustainabilityMetrics (sustainabilityMetric+)>

<!ELEMENT sustainabilityMetric (
    metricId,
    metricName,
    metricValue,
    unit,
    metricDate,
    description
)>

<!ELEMENT metricId (#PCDATA)>
<!ELEMENT metricName (#PCDATA)>
<!ELEMENT metricValue (#PCDATA)>
<!ELEMENT metricDate (#PCDATA)>

=== sandiri-saiteja/Kothii/xml/green-campus.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE greenCampus SYSTEM "green-campus.dtd">

<greenCampus>

    <!-- =====================================================
         RESOURCES
         ===================================================== -->

    <resources>

        <resource>
            <resourceId>2</resourceId>
            <resourceName>Solar Energy</resourceName>
            <resourceType>Renewable Energy</resourceType>
            <unit>kWh</unit>
            <description>Electricity generated from campus solar panels</description>
        </resource>

        <resource>
            <resourceId>3</resourceId>
            <resourceName>Wind Energy</resourceName>
            <resourceType>Renewable Energy</resourceType>
            <unit>kWh</unit>
            <description>Electricity generated by campus wind turbines</description>
        </resource>

        <resource>
            <resourceId>4</resourceId>
            <resourceName>Water</resourceName>
            <resourceType>Natural Resource</resourceType>
            <unit>Litres</unit>
            <description>Water consumed across the campus</description>
        </resource>

    </resources>


    <!-- =====================================================
         CONSUMPTION RECORDS
         ===================================================== -->

    <consumptionRecords>

        <consumptionRecord>
            <recordId>1</recordId>
            <resourceId>2</resourceId>
            <consumptionValue>125.50</consumptionValue>
            <consumptionDate>2026-09-07</consumptionDate>
            <campusLocation>Main Campus</campusLocation>
        </consumptionRecord>

        <consumptionRecord>
            <recordId>2</recordId>
            <resourceId>3</resourceId>
            <consumptionValue>87.25</consumptionValue>
            <consumptionDate>2026-09-08</consumptionDate>
            <campusLocation>Engineering Campus</campusLocation>
        </consumptionRecord>

        <consumptionRecord>
            <recordId>3</recordId>
            <resourceId>4</resourceId>
            <consumptionValue>2500.00</consumptionValue>
            <consumptionDate>2026-09-09</consumptionDate>
            <campusLocation>Main Campus</campusLocation>
        </consumptionRecord>

    </consumptionRecords>


    <!-- =====================================================
         SUSTAINABILITY METRICS
         ===================================================== -->

    <sustainabilityMetrics>

        <sustainabilityMetric>
            <metricId>1</metricId>
            <metricName>Solar Energy Generation</metricName>
            <metricValue>85.75</metricValue>
            <unit>kWh</unit>
            <metricDate>2026-09-07</metricDate>
            <description>Daily solar energy generated on campus</description>
        </sustainabilityMetric>

        <sustainabilityMetric>
            <metricId>2</metricId>
            <metricName>Carbon Emission Reduction</metricName>
            <metricValue>42.30</metricValue>
            <unit>kg CO2</unit>
            <metricDate>2026-09-08</metricDate>
            <description>Estimated carbon emissions avoided through renewable energy</description>
        </sustainabilityMetric>

        <sustainabilityMetric>
            <metricId>3</metricId>
            <metricName>Water Conservation</metricName>
            <metricValue>18.50</metricValue>
            <unit>Percent</unit>
            <metricDate>2026-09-09</metricDate>
            <description>Percentage of water saved through conservation practices</description>
        </sustainabilityMetric>

    </sustainabilityMetrics>

</greenCampus>
